# Generated by Django 5.1.2 on 2024-10-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publisher_rename_summary_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='nationality',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
    ]
